name: lithabit
description: A library books app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  barcode: ^2.2.4
  barcode_widget: ^2.0.4
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdfviewer: ^22.1.34
  http: ^1.0.0
  cached_video_player: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/loader.gif
    - assets/book0.pdf
    - assets/book1.pdf
    - assets/book2.pdf
    - assets/book3.pdf
    - assets/book4.pdf
    - assets/book5.pdf
    - assets/book6.pdf
    - assets/book7.pdf
    - assets/book8.pdf
    - assets/book9.pdf
    - assets/book10.pdf
    - assets/book11.pdf
    - assets/book12.pdf
    - assets/book13.pdf
    - assets/book14.pdf
    - assets/book15.pdf
    - assets/book16.pdf
    - assets/book17.pdf
    - assets/book18.pdf
    - assets/book19.pdf
    - assets/book20.pdf
    - assets/book21.pdf
    - assets/book22.pdf
    - assets/book23.pdf
    - assets/book24.pdf
    - assets/book25.pdf
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"